name: trigger jenkins job
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://ec2-54-244-80-240.us-west-2.compute.amazonaws.com:8080/"
          user: "admin"
          token: ${{ secrets.EC2_JENKINS }}
          job: "MobileTests1"